---
  root: true
  extends:
    - airbnb-base
    - plugin:node/recommended
    - plugin:prettier/recommended
  plugins:
    - node
    - prettier
  rules:
    class-methods-use-this: off
    consistent-return: off
    curly:
      - error
      - all
    max-len:
      - error
      - 110   # keep in sync with .prettierrc.yaml printWidth
      - 2
    node/no-unsupported-features:
      - error
      - version: 4
        ignores:
          - syntax
    # TODO: fix the remaining overrides
    global-require: off
    import/first: off
    import/no-dynamic-require: off
    no-console: off
    no-constant-condition: off
    no-continue: off
    no-empty: off
    no-param-reassign: off
    no-plusplus: off
    no-restricted-syntax: off
    no-return-await: off
    no-shadow: off
    no-underscore-dangle: off
    no-unused-expressions: off
    no-use-before-define: off
    no-useless-concat: off
    prefer-destructuring: off
