---
  root: true
  extends:
    - airbnb-base
    - plugin:node/recommended
    - plugin:prettier/recommended
  plugins:
    - node
    - prettier
  rules:
    class-methods-use-this: off
    consistent-return: off
    curly:
      - error
      - all
    max-len:
      - error
      - 110   # keep in sync with .prettierrc.yaml printWidth
      - 2
    node/no-unsupported-features:
      - error
      - version: 4
        ignores:
          - syntax
    no-param-reassign:
      - error
      - ignorePropertyModificationsFor:
        - err
    no-underscore-dangle:
      - error
      - allowAfterThis: true
    no-use-before-define:
      - error
      - nofunc
