root: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:node/recommended
  - plugin:prettier/recommended
plugins:
  - jest
  - node
  - prettier
rules:
  class-methods-use-this:
    - error
    - exceptMethods:
        - defaultOptions
        - otherCommandConfigs
        - requiresGit
  consistent-return: "off"
  curly:
    - error
    - all
  max-len: "off" # managed by .prettierrc.yaml printWidth
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - err # Error decoration
        - obj # .reduce() object
        - pkg # Package instance
  no-restricted-syntax:
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-use-before-define:
    - error
    - functions: false
      classes: false
  prefer-destructuring: "off"
  prefer-object-spread: "off"
  strict: "off"
overrides:
  - files: "commands/*/command.js"
    rules:
      global-require: "off"
  - files:
      - "integration/**"
      - "**/__tests__/**"
      - "**/__mocks__/**"
      - "**/__helpers__/**"
    env:
      jest: true
    rules:
      # dev dependencies are hoisted to the root
      import/no-extraneous-dependencies: "off"
      # mocked modules are imported before helpers
      import/order: "off"
      max-classes-per-file: "off"
      node/no-extraneous-require: "off"
      node/no-unpublished-require: "off"
      no-console: "off"
  - files:
      - "test/fixtures/**"
      - "**/__fixtures__/**"
    rules:
      global-require: "off"
      import/no-extraneous-dependencies: "off"
      import/no-unresolved: "off"
      node/no-extraneous-require: "off"
      node/no-missing-require:
        - error
        - allowModules:
            - "@integration/package-1"
            - "@integration/package-2"
      no-console: "off"
      strict: "off"
  - files:
      - "utils/map-to-registry/lib/map-to-registry.js"
      - "utils/npm-conf/lib/nerf-dart.js"
    rules:
      # Allow legacy url API
      node/no-deprecated-api: "off"
  - files:
      - "utils/npm-conf/lib/conf.js"
    rules:
      no-useless-catch: "off"
