// flow-typed signature: b0c570e9b145352977658585c70163c0
// flow-typed version: <<STUB>>/async_v^1.5.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async/dist/async' {
  declare module.exports: any;
}

declare module 'async/dist/async.min' {
  declare module.exports: any;
}

declare module 'async/lib/async' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async/dist/async.js' {
  declare module.exports: $Exports<'async/dist/async'>;
}
declare module 'async/dist/async.min.js' {
  declare module.exports: $Exports<'async/dist/async.min'>;
}
declare module 'async/lib/async.js' {
  declare module.exports: $Exports<'async/lib/async'>;
}
