// flow-typed signature: f0299f571e61d4dfbe11fae773c54517
// flow-typed version: <<STUB>>/cmd-shim_v^2.0.2/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cmd-shim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cmd-shim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cmd-shim/test/00-setup' {
  declare module.exports: any;
}

declare module 'cmd-shim/test/basic' {
  declare module.exports: any;
}

declare module 'cmd-shim/test/zz-cleanup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cmd-shim/index' {
  declare module.exports: $Exports<'cmd-shim'>;
}
declare module 'cmd-shim/index.js' {
  declare module.exports: $Exports<'cmd-shim'>;
}
declare module 'cmd-shim/test/00-setup.js' {
  declare module.exports: $Exports<'cmd-shim/test/00-setup'>;
}
declare module 'cmd-shim/test/basic.js' {
  declare module.exports: $Exports<'cmd-shim/test/basic'>;
}
declare module 'cmd-shim/test/zz-cleanup.js' {
  declare module.exports: $Exports<'cmd-shim/test/zz-cleanup'>;
}
