// flow-typed signature: eaeea72895dd4e6146d41705c75a1397
// flow-typed version: <<STUB>>/command-join_v^1.1.1/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-join'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-join' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-join/dist/command-join' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-join/dist/command-join.js' {
  declare module.exports: $Exports<'command-join/dist/command-join'>;
}
