// flow-typed signature: 8ee75980130f8ecfdd4c45c49af7eed8
// flow-typed version: <<STUB>>/cross-env_v^1.0.8/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-env/bin/cross-env' {
  declare module.exports: any;
}

declare module 'cross-env/dist/index' {
  declare module.exports: any;
}

declare module 'cross-env/src/index' {
  declare module.exports: any;
}

declare module 'cross-env/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-env/bin/cross-env.js' {
  declare module.exports: $Exports<'cross-env/bin/cross-env'>;
}
declare module 'cross-env/dist/index.js' {
  declare module.exports: $Exports<'cross-env/dist/index'>;
}
declare module 'cross-env/src/index.js' {
  declare module.exports: $Exports<'cross-env/src/index'>;
}
declare module 'cross-env/src/index.test.js' {
  declare module.exports: $Exports<'cross-env/src/index.test'>;
}
