// flow-typed signature: c48a64d36c7532da8da479e78bf685c5
// flow-typed version: <<STUB>>/cross-spawn_v^4.0.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-spawn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-spawn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-spawn/lib/enoent' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/hasBrokenSpawn' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/parse' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/resolveCommand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-spawn/index' {
  declare module.exports: $Exports<'cross-spawn'>;
}
declare module 'cross-spawn/index.js' {
  declare module.exports: $Exports<'cross-spawn'>;
}
declare module 'cross-spawn/lib/enoent.js' {
  declare module.exports: $Exports<'cross-spawn/lib/enoent'>;
}
declare module 'cross-spawn/lib/hasBrokenSpawn.js' {
  declare module.exports: $Exports<'cross-spawn/lib/hasBrokenSpawn'>;
}
declare module 'cross-spawn/lib/parse.js' {
  declare module.exports: $Exports<'cross-spawn/lib/parse'>;
}
declare module 'cross-spawn/lib/resolveCommand.js' {
  declare module.exports: $Exports<'cross-spawn/lib/resolveCommand'>;
}
