// flow-typed signature: 5486faca50efb1f2b2eae059d5b67c8f
// flow-typed version: <<STUB>>/eslint-config-babel_v^1.0.1/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-babel/index' {
  declare module.exports: $Exports<'eslint-config-babel'>;
}
declare module 'eslint-config-babel/index.js' {
  declare module.exports: $Exports<'eslint-config-babel'>;
}
