// flow-typed signature: 3652e93a67d901646ae4182a510a5cab
// flow-typed version: <<STUB>>/eslint-plugin-babel_v^3.3.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-babel/rules/array-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/arrow-parens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/flow-object-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/func-params-comma-dangle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/generator-star-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/new-cap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/no-await-in-loop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/object-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/rules/object-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/array-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/arrow-parens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/flow-object-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/func-params-comma-dangle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/generator-star-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/new-cap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/no-await-in-loop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/object-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-babel/tests/object-shorthand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-babel/index' {
  declare module.exports: $Exports<'eslint-plugin-babel'>;
}
declare module 'eslint-plugin-babel/index.js' {
  declare module.exports: $Exports<'eslint-plugin-babel'>;
}
declare module 'eslint-plugin-babel/rules/array-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/array-bracket-spacing'>;
}
declare module 'eslint-plugin-babel/rules/arrow-parens.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/arrow-parens'>;
}
declare module 'eslint-plugin-babel/rules/flow-object-type.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/flow-object-type'>;
}
declare module 'eslint-plugin-babel/rules/func-params-comma-dangle.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/func-params-comma-dangle'>;
}
declare module 'eslint-plugin-babel/rules/generator-star-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/generator-star-spacing'>;
}
declare module 'eslint-plugin-babel/rules/new-cap.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/new-cap'>;
}
declare module 'eslint-plugin-babel/rules/no-await-in-loop.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/no-await-in-loop'>;
}
declare module 'eslint-plugin-babel/rules/object-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/object-curly-spacing'>;
}
declare module 'eslint-plugin-babel/rules/object-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/rules/object-shorthand'>;
}
declare module 'eslint-plugin-babel/tests/array-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/array-bracket-spacing'>;
}
declare module 'eslint-plugin-babel/tests/arrow-parens.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/arrow-parens'>;
}
declare module 'eslint-plugin-babel/tests/flow-object-type.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/flow-object-type'>;
}
declare module 'eslint-plugin-babel/tests/func-params-comma-dangle.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/func-params-comma-dangle'>;
}
declare module 'eslint-plugin-babel/tests/generator-star-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/generator-star-spacing'>;
}
declare module 'eslint-plugin-babel/tests/new-cap.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/new-cap'>;
}
declare module 'eslint-plugin-babel/tests/no-await-in-loop.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/no-await-in-loop'>;
}
declare module 'eslint-plugin-babel/tests/object-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/object-curly-spacing'>;
}
declare module 'eslint-plugin-babel/tests/object-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-babel/tests/object-shorthand'>;
}
