// flow-typed signature: 589c1df1f391d77efc73c1392ecc8431
// flow-typed version: <<STUB>>/lodash.find_v^4.3.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.find/index' {
  declare module.exports: $Exports<'lodash.find'>;
}
declare module 'lodash.find/index.js' {
  declare module.exports: $Exports<'lodash.find'>;
}
