// flow-typed signature: 2cd9a85ff7f3cf5f05153959c91cf7d4
// flow-typed version: <<STUB>>/normalize-newline_v^2.1.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-newline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-newline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'normalize-newline/index' {
  declare module.exports: $Exports<'normalize-newline'>;
}
declare module 'normalize-newline/index.js' {
  declare module.exports: $Exports<'normalize-newline'>;
}
