// flow-typed signature: b08ab60d6121110d8aa2392d9fb4b0f6
// flow-typed version: <<STUB>>/normalize-path_v^2.0.1/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'normalize-path/index' {
  declare module.exports: $Exports<'normalize-path'>;
}
declare module 'normalize-path/index.js' {
  declare module.exports: $Exports<'normalize-path'>;
}
