// flow-typed signature: fc6d28a0907a58cd3abeeb5e4df15b73
// flow-typed version: <<STUB>>/object-assign-sorted_v^1.0.0/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-assign-sorted'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-assign-sorted' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object-assign-sorted/index' {
  declare module.exports: $Exports<'object-assign-sorted'>;
}
declare module 'object-assign-sorted/index.js' {
  declare module.exports: $Exports<'object-assign-sorted'>;
}
