// flow-typed signature: 952cade2b6e612723ffbb6aabf857a96
// flow-typed version: <<STUB>>/progress_v^1.1.8/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'progress/lib/node-progress' {
  declare module.exports: any;
}

// Filename aliases
declare module 'progress/index' {
  declare module.exports: $Exports<'progress'>;
}
declare module 'progress/index.js' {
  declare module.exports: $Exports<'progress'>;
}
declare module 'progress/lib/node-progress.js' {
  declare module.exports: $Exports<'progress/lib/node-progress'>;
}
