// flow-typed signature: e445f470948b2d450d29d38e84e3da45
// flow-typed version: <<STUB>>/read-cmd-shim_v^1.0.1/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-cmd-shim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-cmd-shim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'read-cmd-shim/test/integration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'read-cmd-shim/index' {
  declare module.exports: $Exports<'read-cmd-shim'>;
}
declare module 'read-cmd-shim/index.js' {
  declare module.exports: $Exports<'read-cmd-shim'>;
}
declare module 'read-cmd-shim/test/integration.js' {
  declare module.exports: $Exports<'read-cmd-shim/test/integration'>;
}
