// flow-typed signature: ea7d2ba763e65b40cbfe062c0e9d99f8
// flow-typed version: <<STUB>>/signal-exit_v^2.1.2/flow_v0.27.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'signal-exit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'signal-exit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'signal-exit/signals' {
  declare module.exports: any;
}

declare module 'signal-exit/test/all-integration-test' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/awaiter' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/change-code' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/end-of-execution' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/exit-last' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/exit' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/exiter' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/load-unload' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/multiple-load' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/parent' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/sigint' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/sigkill' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/signal-default' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/signal-last' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/signal-listener' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/sigpipe' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/sigterm' {
  declare module.exports: any;
}

declare module 'signal-exit/test/fixtures/unwrap' {
  declare module.exports: any;
}

declare module 'signal-exit/test/multi-exit' {
  declare module.exports: any;
}

declare module 'signal-exit/test/signal-exit-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'signal-exit/index' {
  declare module.exports: $Exports<'signal-exit'>;
}
declare module 'signal-exit/index.js' {
  declare module.exports: $Exports<'signal-exit'>;
}
declare module 'signal-exit/signals.js' {
  declare module.exports: $Exports<'signal-exit/signals'>;
}
declare module 'signal-exit/test/all-integration-test.js' {
  declare module.exports: $Exports<'signal-exit/test/all-integration-test'>;
}
declare module 'signal-exit/test/fixtures/awaiter.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/awaiter'>;
}
declare module 'signal-exit/test/fixtures/change-code.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/change-code'>;
}
declare module 'signal-exit/test/fixtures/end-of-execution.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/end-of-execution'>;
}
declare module 'signal-exit/test/fixtures/exit-last.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/exit-last'>;
}
declare module 'signal-exit/test/fixtures/exit.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/exit'>;
}
declare module 'signal-exit/test/fixtures/exiter.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/exiter'>;
}
declare module 'signal-exit/test/fixtures/load-unload.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/load-unload'>;
}
declare module 'signal-exit/test/fixtures/multiple-load.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/multiple-load'>;
}
declare module 'signal-exit/test/fixtures/parent.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/parent'>;
}
declare module 'signal-exit/test/fixtures/sigint.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/sigint'>;
}
declare module 'signal-exit/test/fixtures/sigkill.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/sigkill'>;
}
declare module 'signal-exit/test/fixtures/signal-default.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/signal-default'>;
}
declare module 'signal-exit/test/fixtures/signal-last.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/signal-last'>;
}
declare module 'signal-exit/test/fixtures/signal-listener.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/signal-listener'>;
}
declare module 'signal-exit/test/fixtures/sigpipe.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/sigpipe'>;
}
declare module 'signal-exit/test/fixtures/sigterm.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/sigterm'>;
}
declare module 'signal-exit/test/fixtures/unwrap.js' {
  declare module.exports: $Exports<'signal-exit/test/fixtures/unwrap'>;
}
declare module 'signal-exit/test/multi-exit.js' {
  declare module.exports: $Exports<'signal-exit/test/multi-exit'>;
}
declare module 'signal-exit/test/signal-exit-test.js' {
  declare module.exports: $Exports<'signal-exit/test/signal-exit-test'>;
}
