name: "Install node and dependencies"
description: Install node and dependencies
inputs:
  node-version:
    description: "A specific version of node to install (rather than the value specified in the volta config in package.json)"
    required: false
  install-command:
    description: "The command to run to install dependencies"
    required: false
    default: "npm ci"

runs:
  using: "composite"
  steps:
    - name: Install node and npm based on the given values (or the volta config in package.json)
      uses: volta-cli/action@v4
      with:
        node-version: ${{ inputs.node-version }}

    # Github actions/cache now recommends _not_ caching node_modules when using npm ci
    # https://github.com/actions/cache/blob/940f3d7cf195ba83374c77632d1e2cbb2f24ae68/examples.md#node---npm

    - name: Install dependencies
      run: ${{ inputs.install-command }}
      shell: bash

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash
