/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // main: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  main: [
    "introduction",
    "getting-started",
    {
      type: "category",
      label: "How To...",
      items: [
        "how-to/bootstrap",
        "how-to/run-tasks",
        "how-to/version-and-publish",
        "how-to/enable-dte",
      ],
      link: {
        type: "generated-index",
        title: "How To Guides",
        description: "Get Started",
        slug: "/how-to",
      },
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "core-concepts/computation-caching",
      ],
      link: {
        type: "generated-index",
        title: "Core Concepts",
        description: "Learn about the most important core concepts of Lerna!",
        slug: "/core-concepts",
        keywords: ["core", "caching", "dte", "versioning", "publishing"],
      },
    },
    {
      type: "category",
      label: "API Reference",
      items: ["api-reference/commands", "api-reference/filter-options", "api-reference/configuration"],
    },
    {
      type: "doc",
      label: "FAQ",
      id: "faq",
    },
    "troubleshooting",
  ],
};

module.exports = sidebars;
