name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

env:
  SKIP_POSTINSTALL: true

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need the tags to be available but not the full tree
          filter: "tree:0"

      - name: Install primary node version (see volta config in package.json) and dependencies
        uses: ./.github/actions/install-node-and-dependencies

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: 20
          allowed_tools: "Edit,Read,Write,Glob,Grep,LS,MultiEdit,Bash(pnpm install),Bash(pnpm --version),Bash(pnpm build),Bash(pnpm test),Bash(pnpm e2e),Bash(pnpm update-e2e-snapshots),Bash(pnpm lint),Bash(pnpm typecheck),Bash(pnpm format),Bash(pnpm format-check),Bash(pnpm update-rule-docs),Bash(pnpm check-rule-docs),Bash(pnpm update-rule-lists),Bash(pnpm check-rule-lists),Bash(pnpm update-rule-configs),Bash(pnpm check-rule-configs),Bash(pnpm nx:*),Bash(git status),Bash(git add .),Bash(git commit -m),Bash(git diff),Bash(git log --oneline -10),Bash(node --version)"
